### ISSUE TITLE
Typed property $form must not be accessed before initialization

### ISSUE THREAD

**Issue by aplitax** [nextras/forms-rendering#14]
Typed property Nette\Forms\Rendering\DefaultFormRenderer::$form must not be accessed before initialization:

https://github.com/nextras/forms-rendering/blob/b70cc5184b30c70cd14b23feb88e19d36df490c5/src/Renderers/Bs4FormRenderer.php#L68

Nette Forms 3.2.0

**Comment by repli2dev** [comment]
@hrach Shouldn't there be rather
```
if (!isset($this->form) || $this->form !== $form) {
```

**Comment by hrach** [comment]
Please feel free to send PR :)

**Comment by repli2dev** [comment]
Thanks for affirmation -- prepared.

**Comment by hrach** [comment]
Close by https://github.com/nextras/forms-rendering/pull/16
