### ISSUE TITLE
Missing Bs5FormRenderer.php in Composer installation

### ISSUE THREAD

**Issue by korinektomas** [nextras/forms-rendering#5]
After installation the package via Composer, BS5 renderer is missing. Is there maybe a different version than on GitHub?

**Comment by hrach** [comment]
are you installing dev-master? I've just used it yestreday and it worked.

**Comment by korinektomas** [comment]
Ah, ok. In dev-master it is included... I was confused by installation instructions and just run default composer task in description without checking whether dev-master is the same as 1.0.0... The dev-master works well.

**Comment by hrach** [comment]
Released: https://github.com/nextras/forms-rendering/releases/tag/v1.1.0
